export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';

export const REQUEST_ROBOT_PENDING = 'REQUEST_ROBOT_PENDING';
export const REQUEST_ROBOT_SUCCESS = 'REQUEST_ROBOT_SUCCESS';
export const REQUEST_ROBOT_FAIL = 'REQUEST_ROBOT_FAIL';
